apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-service
  labels:
    app: retail-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-service
  template:
    metadata:
      labels:
        app: retail-service
    spec:
      containers:
        - name: retail-service
          image: retail-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          
