apiVersion: v1
kind: Service
metadata:
  name: retail-service
  labels:
    app: retail-service
spec:
  type: ClusterIP
  selector:
    app: retail-service
  ports:
  - protocol: TCP
    port: 7070
    targetPort: 31000
