node {
      def mvnHome
    
    
    

   
  
        stage('Prepare') {
            
              git url: 'https://github.com/HimanshuChauhan0/retail_management_app-1.git', branch:'himanshu'
              mvnHome = tool 'mvn' 
            
        }
        
        stage('Build') {
           
            if(isUnix()) {
                sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
              }
              else {
              bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
              }
            
        }
        
        
        stage('Unit Test'){
           
          junit '**/target/surefire-reports/TEST-*.xml'
          archive 'target/*.jar' 
            
        }
        
        stage('Integration Test') {
            
            if(isUnix()) {
                sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean verify"
              }
              else {
              bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean verify/)
              }
            
        
        
        
    }
    stage('SonarQube Analysis') {



if(isUnix()) {

sh "'${mvnHome}/bin/mvn' sonar:sonar"

}

else {

bat(/"${mvnHome}\bin\mvn" sonar:sonar /)

}

}

stage('Docker Build'){

if (isUnix()) {

sh "'${mvnHome}/bin/mvn' spring-boot:build-image"
} else {

bat(/"${mvnHome}\bin\mvn" spring-boot:build-images /)
}

}

    
}