node {
      def mvnHome
    
    
    

   
  
        stage('Prepare') {
            
              git url: 'https://github.com/krishnamurthypradeep/migration-devops-ci-cd-monitoring.git', branch:'master'
              mvnHome = tool 'mvn' 
            
        }
        
        stage('Build') {
           
            if(isUnix()) {
                sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
              }
              else {
              bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
              }
            
        }
        
        
        stage('Unit Test'){
           
          junit '**/target/surefire-reports/TEST-*.xml'
          archive 'target/*.jar' 
            
        }
        
        stage('Integration Test') {
            
            if(isUnix()) {
                sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean verify"
              }
              else {
              bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean verify/)
              }
            
        
        
        
    }
    stage('SonarQube Analysis') {



if(isUnix()) {

sh "'${mvnHome}/bin/mvn' sonar:sonar"

}

else {

bat(/"${mvnHome}\bin\mvn" sonar:sonar /)

}

}

stage('Docker Build'){

if (isUnix()) {

sh "'${mvnHome}/bin/mvn' spring-boot:build-image"
} else {

bat(/"${mvnHome}\bin\mvn" spring-boot:build-image /)
}

}


stage('Load Docker Image'){

if (isUnix()) {

sh "minikube image load retail-service"
} else {

bat(/minikube image load retail-service/)
}

}
stage('Kubernetes Pod'){

if (isUnix()) {

sh "kubectl apply -f k8s/deployment.yml"
} else {

bat(/kubectl apply -f k8s/deployment.yml/)
}

}
stage('KubernetesService'){

if (isUnix()) {

sh "kubectl apply -f k8s/service.yml"
} else {

bat(/kubectl apply -f k8s/service.yml/)
}

}

stage('Kubernetes PortForward'){

if (isUnix()) {

sh "kubectl port-forward service/retail-service 7070:31000"
} else {

bat(/kubectl port-forward service/retail-service 7070:31000/)
}

}
    
}